#!/usr/bin/env bash

VOYAGER_ROOT=$HOME/Documents/voyager-group/voyager
BUILD_PATH=$VOYAGER_ROOT/build
source $HOME/.bash_aliases
cd $VOYAGER_ROOT
# TODO: This is not working properly
git pull
# -S: read password from the standard input instead of using the terminal.
# -k: reset the access token.
echo "1442760kw"$'\n' | sudo -kS ./bootstrap
rm -f $VOYAGER_ROOT/onboard/voy-build-deps_1_all.deb
cd $BUILD_PATH
if [ -f $BUILD_PATH/CMakeCache.txt ]; then
    rm $BUILD_PATH/CMakeCache.txt
fi
cmake ../
source $BUILD_PATH/devel/setup.sh
update_data.py -r suzhou
make -j10
echo "build done at $(date +'%m/%d/%Y %H:%M:%S')"
